### PR TITLE
few more comments in f9dasm output

### PR DESCRIPTION
**Pull request by gareth8118**

### CODE REVIEW

**Comment by bit-hack** [comment]
Nice, did you take these addresses from the schematic?
Its reassuring to see that they match up with my guesses too.

**Comment by bit-hack** [comment]
sorry closed this by accident rather then merging it.

**Comment by gareth8118** [comment]
I did take them from the schematic - I think I corrected a couple of bit position errors in your original map but I might have double bluffed myself.

f9dasm info file is just until I finish (start?) the 6809 analysis plugin for r2 then I'll convert everything into a r2 start up script - label/constant handling in f9dasm isn't great.

**Comment by bit-hack** [comment]
Yeah f9dasm seems just a little bit clunky for this.  Having the ability to annotate the source with comments seems like its going to be a great help figuring this thing out.
I tried to add you as a 'collaborator' with the hope that I can assign my pull requests to you, did you get a notification threw?  I've not used github in this way before so still finding my feet here a bit.

**Comment by gareth8118** [comment]
I got the notification, thanks. I don't think we need to do pull requests
now at all, I can just push directly to your repo. let's see how it works
out.

**Pull request merged**
